package cz.zcu.kiv.eeg.owlimport.gui.sources;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import cz.zcu.kiv.eeg.owlimport.gui.ISourceParamsComponent;
import cz.zcu.kiv.eeg.owlimport.gui.ValidationException;
import cz.zcu.kiv.eeg.owlimport.model.sources.ISourceParams;
import cz.zcu.kiv.eeg.owlimport.model.sources.remote.UrlSourceParams;

import javax.swing.*;
import java.awt.*;

/**
 * @author Jan Smitka <jan@smitka.org>
 */
public class UrlParamsComponent implements ISourceParamsComponent {
	private JTextField urlField;
	private JPanel contentPane;

	@Override
	public void validate() throws ValidationException {
		if (urlField.getText().length() == 0) {
			throw new ValidationException("You have enter URL referencing the OWL file you want to import.", urlField);
		}
	}

	@Override
	public JComponent getPanel() {
		return $$$getRootComponent$$$();
	}

	@Override
	public ISourceParams getParams() {
		UrlSourceParams params = new UrlSourceParams();
		params.setUrl(urlField.getText());
		return params;
	}

	{
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
		$$$setupUI$$$();
	}

	/**
	 * Method generated by IntelliJ IDEA GUI Designer
	 * >>> IMPORTANT!! <<<
	 * DO NOT edit this method OR call it in your code!
	 *
	 * @noinspection ALL
	 */
	private void $$$setupUI$$$() {
		contentPane = new JPanel();
		contentPane.setLayout(new GridLayoutManager(1, 2, new Insets(10, 10, 10, 0), -1, -1));
		final JLabel label1 = new JLabel();
		label1.setText("URL:");
		contentPane.add(label1, new GridConstraints(0, 0, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_NONE, GridConstraints.SIZEPOLICY_FIXED, GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
		urlField = new JTextField();
		contentPane.add(urlField, new GridConstraints(0, 1, 1, 1, GridConstraints.ANCHOR_WEST, GridConstraints.FILL_HORIZONTAL, GridConstraints.SIZEPOLICY_WANT_GROW, GridConstraints.SIZEPOLICY_FIXED, null, new Dimension(150, -1), null, 0, false));
	}

	/**
	 * @noinspection ALL
	 */
	public JComponent $$$getRootComponent$$$() {
		return contentPane;
	}
}
